#!/bin/sh
# Map site .env values to NUXT_* for Nitro runtimeConfig overrides at process start.
# (Replaces PM2 ecosystem.config.cjs env mapping for Nuxt sites on dpanel.)

_nuxt_set() {
  nuxt_key="$1"
  val="$2"
  eval "current=\${$nuxt_key-}"
  if [ -z "$current" ] && [ -n "$val" ]; then
    export "$nuxt_key=$val"
  fi
}

_nuxt_set NUXT_SESSION_SECRET "$SESSION_SECRET"
_nuxt_set NUXT_MONGODB_URI "$MONGODB_URI"
_nuxt_set NUXT_MONGODB_DB_NAME "$MONGODB_DB_NAME"
_nuxt_set NUXT_HUB_BASE_DOMAIN "$HUB_BASE_DOMAIN"
_nuxt_set NUXT_ADMIN_HOST "$ADMIN_HOST"
_nuxt_set NUXT_APP_PORT "$APP_PORT"
_nuxt_set NUXT_GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
_nuxt_set NUXT_GOOGLE_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET"
_nuxt_set NUXT_GOOGLE_REDIRECT_URI "$GOOGLE_REDIRECT_URI"
_nuxt_set NUXT_APP_URL "$APP_URL"
_nuxt_set NUXT_PAYPAL_PLAN_MODE "$PAYPAL_PLAN_MODE"
_nuxt_set NUXT_PAYPAL_PLAN_CURRENCY "$PAYPAL_PLAN_CURRENCY"
_nuxt_set NUXT_PAYPAL_PLAN_SANDBOX_CLIENT_ID "$PAYPAL_PLAN_SANDBOX_CLIENT_ID"
_nuxt_set NUXT_PAYPAL_PLAN_SANDBOX_SECRET "$PAYPAL_PLAN_SANDBOX_SECRET"
_nuxt_set NUXT_PAYPAL_PLAN_SANDBOX_WEBHOOK_ID "$PAYPAL_PLAN_SANDBOX_WEBHOOK_ID"
_nuxt_set NUXT_PAYPAL_PLAN_LIVE_CLIENT_ID "$PAYPAL_PLAN_LIVE_CLIENT_ID"
_nuxt_set NUXT_PAYPAL_PLAN_LIVE_SECRET "$PAYPAL_PLAN_LIVE_SECRET"
_nuxt_set NUXT_PAYPAL_PLAN_LIVE_WEBHOOK_ID "$PAYPAL_PLAN_LIVE_WEBHOOK_ID"
_nuxt_set NUXT_FCM_SERVICE_ACCOUNT_JSON "$FCM_SERVICE_ACCOUNT_JSON"
_nuxt_set NUXT_FCM_SERVICE_ACCOUNT_PATH "$FCM_SERVICE_ACCOUNT_PATH"
_nuxt_set NUXT_SYSTEM_ADMIN_EMAILS "$SYSTEM_ADMIN_EMAILS"
_nuxt_set NUXT_OBJECT_STORAGE_BUCKET "$OBJECT_STORAGE_BUCKET"
_nuxt_set NUXT_OBJECT_STORAGE_ACCESS_KEY_ID "$OBJECT_STORAGE_ACCESS_KEY_ID"
_nuxt_set NUXT_OBJECT_STORAGE_SECRET_ACCESS_KEY "$OBJECT_STORAGE_SECRET_ACCESS_KEY"
_nuxt_set NUXT_OBJECT_STORAGE_ENDPOINT "$OBJECT_STORAGE_ENDPOINT"
_nuxt_set NUXT_PUBLIC_HUB_BASE_DOMAIN "$HUB_BASE_DOMAIN"
_nuxt_set NUXT_PUBLIC_ADMIN_HOST "$ADMIN_HOST"
_nuxt_set NUXT_PUBLIC_CDN_MEDIA_URL "$CDN_MEDIA_URL"
