#!/usr/bin/env bash
# Apply data/panel/fail2ban-settings.json to host fail2ban configs and reload.
set -euo pipefail

STACK_ROOT="${STACK_ROOT:-/opt/stack}"
SETTINGS="${STACK_ROOT}/data/panel/fail2ban-settings.json"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=host-chroot.sh
source "${SCRIPT_DIR}/host-chroot.sh"

die() { echo "{\"ok\":false,\"error\":\"$*\"}" >&2; exit 1; }

[[ -f "${SETTINGS}" ]] || die "Settings file not found"

APPLY_CMD="
set -euo pipefail
export STACK=${STACK_ROOT}
SETTINGS=\"\${STACK}/data/panel/fail2ban-settings.json\"
command -v fail2ban-client >/dev/null 2>&1 || { echo fail2ban_not_installed >&2; exit 1; }
command -v python3 >/dev/null 2>&1 || { echo python3_required >&2; exit 1; }

python3 << 'PYAPPLY'
import json, os, datetime, subprocess, sys

stack = os.environ.get('STACK', '/opt/stack')
settings_path = os.path.join(stack, 'data', 'panel', 'fail2ban-settings.json')

with open(settings_path, 'r', encoding='utf-8') as f:
    settings = json.load(f)

ignoreip = settings.get('ignoreip') or ['127.0.0.1/8', '::1']
jails = settings.get('jails') or {}

dpanel_jails = {'nginx-dpanel-login', 'nginx-php-exploit'}
nginx_defaults = {
    'nginx-dpanel-login': {'maxretry': 5, 'findtime': 600, 'bantime': 3600},
    'nginx-php-exploit': {'maxretry': 10, 'findtime': 600, 'bantime': 7200},
}

def jail_cfg(name):
    base = dict(jails.get(name) or {})
    if name in nginx_defaults:
        base = {**nginx_defaults[name], **base}
    return base

def bool_str(v):
    return 'true' if v else 'false'

dpanel_conf = '# dpanel-managed jails — generated by panel\\n'
for name in sorted(dpanel_jails):
    cfg = jail_cfg(name)
    enabled = cfg.get('enabled', True)
    maxretry = int(cfg.get('maxretry', 5))
    findtime = int(cfg.get('findtime', 600))
    bantime = int(cfg.get('bantime', 3600))
    dpanel_conf += f'''
[{name}]
enabled = {bool_str(enabled)}
port = http,8443
filter = {name}
logpath = {stack}/logs/nginx/access.log
maxretry = {maxretry}
findtime = {findtime}
bantime = {bantime}
'''

ignoreip_conf = '# dpanel global ignoreip — generated by panel\\n[DEFAULT]\\nignoreip = ' + ' '.join(str(x) for x in ignoreip) + '\\n'

override_conf = '# dpanel jail overrides — generated by panel\\n'
for name, cfg in sorted(jails.items()):
    if name in dpanel_jails:
        continue
    enabled = cfg.get('enabled', True)
    maxretry = int(cfg.get('maxretry', 5))
    findtime = int(cfg.get('findtime', 600))
    bantime = int(cfg.get('bantime', 3600))
    override_conf += f'''
[{name}]
enabled = {bool_str(enabled)}
maxretry = {maxretry}
findtime = {findtime}
bantime = {bantime}
'''

ts = datetime.datetime.utcnow().strftime('%Y%m%dT%H%M%SZ')
backup_dir = os.path.join(stack, 'data', 'panel', 'fail2ban-backups', ts)
os.makedirs(backup_dir, exist_ok=True)

files = {
    '/etc/fail2ban/jail.d/dpanel.conf': dpanel_conf,
    '/etc/fail2ban/jail.d/dpanel-ignoreip.conf': ignoreip_conf,
    '/etc/fail2ban/jail.d/dpanel-overrides.conf': override_conf,
}

warnings = []
for path, content in files.items():
    base = os.path.basename(path)
    if os.path.isfile(path):
        try:
            with open(path, 'r', encoding='utf-8') as rf:
                old = rf.read()
            with open(os.path.join(backup_dir, base), 'w', encoding='utf-8') as wf:
                wf.write(old)
        except OSError:
            pass
    with open(path, 'w', encoding='utf-8') as wf:
        wf.write(content)

try:
    subprocess.run(['fail2ban-client', 'reload'], check=True, capture_output=True, text=True)
except subprocess.CalledProcessError as e:
    err = (e.stderr or e.stdout or str(e)).strip()
    for path in files:
        base = os.path.basename(path)
        bak = os.path.join(backup_dir, base)
        if os.path.isfile(bak):
            with open(bak, 'r', encoding='utf-8') as rf:
                with open(path, 'w', encoding='utf-8') as wf:
                    wf.write(rf.read())
    try:
        subprocess.run(['fail2ban-client', 'reload'], capture_output=True, text=True)
    except Exception:
        pass
    print(json.dumps({'ok': False, 'error': f'fail2ban reload failed: {err[:500]}'}))
    sys.exit(1)

active = subprocess.run(['systemctl', 'is-active', 'fail2ban'], capture_output=True, text=True)
if active.stdout.strip() != 'active':
    warnings.append('fail2ban service is not active after reload')

print(json.dumps({'ok': True, 'reloaded': True, 'warnings': warnings, 'backupDir': backup_dir}))
PYAPPLY
"

if [[ -f /.dockerenv ]] && command -v docker >/dev/null 2>&1; then
  OUT="$(host_exec_capture "${APPLY_CMD}")" || die "${OUT:-Apply failed}"
else
  OUT="$(bash -lc "${APPLY_CMD}" 2>&1)" || die "${OUT:-Apply failed}"
fi

# Print last JSON line from output
echo "${OUT}" | grep -E '^\{.*\}$' | tail -1 || die "Apply did not return JSON"
